name: Build Test

on: [push, pull_request_target, workflow_dispatch]

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: |
          make frontend_preinstall
      - name: Build dist
        run: |
          make frontend

      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run sccache-cache
        uses: mozilla/sccache-action@v0.0.1
        with:
          version: "v0.4.0-pre.6"
      - name: Build Debug App
        run: TARGET=release make build
      - name: Archive App File
        uses: actions/upload-artifact@v3
        with:
          name: book-searcher
          path: target/release/book-searcher
      - name: Run sccache stat for check
        shell: bash
        run: ${SCCACHE_PATH} --show-stats
